<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>CoolProp wrapper for C#</Description>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NoWarn>$(NoWarn);1591;NU5129;NU5131;CA2101;SYSLIB1054;IDE0130;IDE0330;CS8981</NoWarn>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <Summary>CoolProp wrapper for C#</Summary>
    <Title>SharpProp</Title>
    <TargetsForTfmSpecificContentInPackage>
      $(TargetsForTfmSpecificContentInPackage);SharpPropPackManagedAssemblies
    </TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>
  <Target Name="SharpPropPackManagedAssemblies">
    <ItemGroup>
      <TfmSpecificPackageFile
        Include="$(IntermediateOutputPath)ref\$(TargetFileName)"
        PackagePath="ref\$(TargetFramework)\"
      />
      <TfmSpecificPackageFile
        Include="$(OutputPath)$(TargetFileName)"
        PackagePath="runtimes\any\lib\$(TargetFramework)\"
      />
      <TfmSpecificPackageFile
        Include="$(OutputPath)$(AssemblyName).xml"
        PackagePath="runtimes\any\lib\$(TargetFramework)\"
        Condition="Exists('$(OutputPath)$(AssemblyName).xml')"
      />
    </ItemGroup>
  </Target>
  <ItemGroup>
    <None Include="runtimes\**\native\*" Pack="true" PackagePath="%(Identity)" Visible="false" />
    <None
      Include="buildTransitive\SharpProp.targets"
      Pack="true"
      PackagePath="buildTransitive\SharpProp.targets"
      Visible="false"
    />
  </ItemGroup>
  <ItemGroup Condition="'$(RuntimeIdentifier)' != ''">
    <None
      Include="runtimes\$(RuntimeIdentifier)\native\*"
      CopyToOutputDirectory="PreserveNewest"
      Pack="false"
      TargetPath="%(Filename)%(Extension)"
      Visible="false"
    />
  </ItemGroup>
  <ItemGroup Condition="'$(RuntimeIdentifier)' == '' and '$(NETCoreSdkRuntimeIdentifier)' != ''">
    <None
      Include="runtimes\$(NETCoreSdkRuntimeIdentifier)\native\*"
      CopyToOutputDirectory="PreserveNewest"
      Pack="false"
      TargetPath="%(Filename)%(Extension)"
      Visible="false"
    />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="SharpProp.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Enums.NET" Version="5.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="UnitsNet" Version="5.75.0" />
    <PackageReference Include="UnitsNet.Serialization.JsonNet" Version="5.50.0" />
    <PackageReference Include="UnitsNet.NumberExtensions" Version="5.75.0" />
  </ItemGroup>
</Project>
