<Project>
  <PropertyGroup>
    <Authors>Vladimir Portyanikhin</Authors>
    <Copyright>Copyright (c) Vladimir Portyanikhin 2026</Copyright>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/portyanikhin/sharpprop</PackageProjectUrl>
    <PackageReleaseNotes>
      Release notes can be found at https://github.com/portyanikhin/sharpprop/releases
    </PackageReleaseNotes>
    <PackageTags>
      native cross-platform CoolProp fluids mixtures humid air thermophysical properties thermodynamics
    </PackageTags>
    <PackageVersion>9.0.0</PackageVersion>
    <RepositoryUrl>https://github.com/portyanikhin/sharpprop</RepositoryUrl>
  </PropertyGroup>
</Project>
