using System.Diagnostics.CodeAnalysis;
using SharpProp.Attributes;

namespace SharpProp
{
    /// <summary>
    ///     List of CoolProp fluids
    /// </summary>
    /// <seealso href="http://www.coolprop.org/fluid_properties/PurePseudoPure.html">coolprop.org</seealso>
    /// <seealso href="http://www.coolprop.org/fluid_properties/Incompressibles.html">coolprop.org</seealso>
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    public enum FluidsList
    {
        // Pure and pseudo-pure fluids
        [FluidInfo("Acetone")] Acetone,
        [FluidInfo("Air")] Air,
        [FluidInfo("Ammonia")] Ammonia,
        [FluidInfo("Argon")] Argon,
        [FluidInfo("Benzene")] Benzene,
        [FluidInfo("1-Butene")] Butene,
        [FluidInfo("CarbonDioxide")] CarbonDioxide,
        [FluidInfo("CarbonMonoxide")] CarbonMonoxide,
        [FluidInfo("CarbonylSulfide")] CarbonylSulfide,
        [FluidInfo("cis-2-Butene")] cis2Butene,
        [FluidInfo("CycloHexane")] CycloHexane,
        [FluidInfo("CycloPentane")] CycloPentane,
        [FluidInfo("CycloPropane")] CycloPropane,
        [FluidInfo("D4")] D4,
        [FluidInfo("D5")] D5,
        [FluidInfo("D6")] D6,
        [FluidInfo("Deuterium")] Deuterium,
        [FluidInfo("Dichloroethane")] Dichloroethane,
        [FluidInfo("DiethylEther")] DiethylEther,
        [FluidInfo("DimethylCarbonate")] DimethylCarbonate,
        [FluidInfo("DimethylEther")] DimethylEther,
        [FluidInfo("Ethane")] Ethane,
        [FluidInfo("Ethanol")] Ethanol,
        [FluidInfo("EthylBenzene")] EthylBenzene,
        [FluidInfo("Ethylene")] Ethylene,
        [FluidInfo("EthyleneOxide")] EthyleneOxide,
        [FluidInfo("Fluorine")] Fluorine,
        [FluidInfo("HeavyWater")] HeavyWater,
        [FluidInfo("Helium")] Helium,
        [FluidInfo("HFE143m")] HFE143m,
        [FluidInfo("Hydrogen")] Hydrogen,
        [FluidInfo("HydrogenChloride")] HydrogenChloride,
        [FluidInfo("HydrogenSulfide")] HydrogenSulfide,
        [FluidInfo("IsoButane")] IsoButane,
        [FluidInfo("IsoButene")] IsoButene,
        [FluidInfo("Isohexane")] Isohexane,
        [FluidInfo("Isopentane")] Isopentane,
        [FluidInfo("Krypton")] Krypton,
        [FluidInfo("MD2M")] MD2M,
        [FluidInfo("MD3M")] MD3M,
        [FluidInfo("MD4M")] MD4M,
        [FluidInfo("MDM")] MDM,
        [FluidInfo("Methane")] Methane,
        [FluidInfo("Methanol")] Methanol,
        [FluidInfo("MethylLinoleate")] MethylLinoleate,
        [FluidInfo("MethylLinolenate")] MethylLinolenate,
        [FluidInfo("MethylOleate")] MethylOleate,
        [FluidInfo("MethylPalmitate")] MethylPalmitate,
        [FluidInfo("MethylStearate")] MethylStearate,
        [FluidInfo("MM")] MM,
        [FluidInfo("m-Xylene")] mXylene,
        [FluidInfo("n-Butane")] nButane,
        [FluidInfo("n-Decane")] nDecane,
        [FluidInfo("n-Dodecane")] nDodecane,
        [FluidInfo("Neon")] Neon,
        [FluidInfo("Neopentane")] Neopentane,
        [FluidInfo("n-Heptane")] nHeptane,
        [FluidInfo("n-Hexane")] nHexane,
        [FluidInfo("Nitrogen")] Nitrogen,
        [FluidInfo("NitrousOxide")] NitrousOxide,
        [FluidInfo("n-Nonane")] nNonane,
        [FluidInfo("n-Octane")] nOctane,
        [FluidInfo("Novec649")] Novec649,
        [FluidInfo("n-Pentane")] nPentane,
        [FluidInfo("n-Propane")] nPropane,
        [FluidInfo("n-Undecane")] nUndecane,
        [FluidInfo("OrthoDeuterium")] OrthoDeuterium,
        [FluidInfo("OrthoHydrogen")] OrthoHydrogen,
        [FluidInfo("Oxygen")] Oxygen,
        [FluidInfo("o-Xylene")] oXylene,
        [FluidInfo("ParaDeuterium")] ParaDeuterium,
        [FluidInfo("ParaHydrogen")] ParaHydrogen,
        [FluidInfo("Propylene")] Propylene,
        [FluidInfo("Propyne")] Propyne,
        [FluidInfo("p-Xylene")] pXylene,
        [FluidInfo("R11")] R11,
        [FluidInfo("R113")] R113,
        [FluidInfo("R114")] R114,
        [FluidInfo("R115")] R115,
        [FluidInfo("R116")] R116,
        [FluidInfo("R12")] R12,
        [FluidInfo("R123")] R123,
        [FluidInfo("R1233zd(E)")] R1233zdE,
        [FluidInfo("R1234yf")] R1234yf,
        [FluidInfo("R1234ze(E)")] R1234zeE,
        [FluidInfo("R1234ze(Z)")] R1234zeZ,
        [FluidInfo("R124")] R124,
        [FluidInfo("R1243zf")] R1243zf,
        [FluidInfo("R125")] R125,
        [FluidInfo("R13")] R13,
        [FluidInfo("R134a")] R134a,
        [FluidInfo("R13I1")] R13I1,
        [FluidInfo("R14")] R14,
        [FluidInfo("R141b")] R141b,
        [FluidInfo("R142b")] R142b,
        [FluidInfo("R143a")] R143a,
        [FluidInfo("R152A")] R152A,
        [FluidInfo("R161")] R161,
        [FluidInfo("R21")] R21,
        [FluidInfo("R218")] R218,
        [FluidInfo("R22")] R22,
        [FluidInfo("R227EA")] R227EA,
        [FluidInfo("R23")] R23,
        [FluidInfo("R236EA")] R236EA,
        [FluidInfo("R236FA")] R236FA,
        [FluidInfo("R245ca")] R245ca,
        [FluidInfo("R245fa")] R245fa,
        [FluidInfo("R32")] R32,
        [FluidInfo("R365MFC")] R365MFC,
        [FluidInfo("R40")] R40,
        [FluidInfo("R404A")] R404A,
        [FluidInfo("R407C")] R407C,
        [FluidInfo("R41")] R41,
        [FluidInfo("R410A")] R410A,
        [FluidInfo("R507A")] R507A,
        [FluidInfo("RC318")] RC318,
        [FluidInfo("SES36")] SES36,
        [FluidInfo("SulfurDioxide")] SulfurDioxide,
        [FluidInfo("SulfurHexafluoride")] SulfurHexafluoride,
        [FluidInfo("Toluene")] Toluene,
        [FluidInfo("trans-2-Butene")] trans2Butene,
        [FluidInfo("Water")] Water,
        [FluidInfo("Xenon")] Xenon,

        // Incompressible pure fluids
        [FluidInfo("AS10", "INCOMP")] AS10,
        [FluidInfo("AS20", "INCOMP")] AS20,
        [FluidInfo("AS30", "INCOMP")] AS30,
        [FluidInfo("AS40", "INCOMP")] AS40,
        [FluidInfo("AS55", "INCOMP")] AS55,
        [FluidInfo("DEB", "INCOMP")] DEB,
        [FluidInfo("DowJ", "INCOMP")] DowJ,
        [FluidInfo("DowJ2", "INCOMP")] DowJ2,
        [FluidInfo("DowQ", "INCOMP")] DowQ,
        [FluidInfo("DowQ2", "INCOMP")] DowQ2,
        [FluidInfo("DSF", "INCOMP")] DSF,
        [FluidInfo("HC10", "INCOMP")] HC10,
        [FluidInfo("HC20", "INCOMP")] HC20,
        [FluidInfo("HC30", "INCOMP")] HC30,
        [FluidInfo("HC40", "INCOMP")] HC40,
        [FluidInfo("HC50", "INCOMP")] HC50,
        [FluidInfo("HCB", "INCOMP")] HCB,
        [FluidInfo("HCM", "INCOMP")] HCM,
        [FluidInfo("HFE", "INCOMP")] HFE,
        [FluidInfo("HFE2", "INCOMP")] HFE2,
        [FluidInfo("HY20", "INCOMP")] HY20,
        [FluidInfo("HY30", "INCOMP")] HY30,
        [FluidInfo("HY40", "INCOMP")] HY40,
        [FluidInfo("HY45", "INCOMP")] HY45,
        [FluidInfo("HY50", "INCOMP")] HY50,
        [FluidInfo("NaK", "INCOMP")] NaK,
        [FluidInfo("NBS", "INCOMP")] NBS,
        [FluidInfo("PBB", "INCOMP")] PBB,
        [FluidInfo("PCL", "INCOMP")] PCL,
        [FluidInfo("PCR", "INCOMP")] PCR,
        [FluidInfo("PGLT", "INCOMP")] PGLT,
        [FluidInfo("PHE", "INCOMP")] PHE,
        [FluidInfo("PHR", "INCOMP")] PHR,
        [FluidInfo("PLR", "INCOMP")] PLR,
        [FluidInfo("PMR", "INCOMP")] PMR,
        [FluidInfo("PMS1", "INCOMP")] PMS1,
        [FluidInfo("PMS2", "INCOMP")] PMS2,
        [FluidInfo("PNF", "INCOMP")] PNF,
        [FluidInfo("PNF2", "INCOMP")] PNF2,
        [FluidInfo("S800", "INCOMP")] S800,
        [FluidInfo("SAB", "INCOMP")] SAB,
        [FluidInfo("T66", "INCOMP")] T66,
        [FluidInfo("T72", "INCOMP")] T72,
        [FluidInfo("TCO", "INCOMP")] TCO,
        [FluidInfo("TD12", "INCOMP")] TD12,
        [FluidInfo("TVP1", "INCOMP")] TVP1,
        [FluidInfo("TVP1869", "INCOMP")] TVP1869,
        [FluidInfo("TX22", "INCOMP")] TX22,
        [FluidInfo("TY10", "INCOMP")] TY10,
        [FluidInfo("TY15", "INCOMP")] TY15,
        [FluidInfo("TY20", "INCOMP")] TY20,
        [FluidInfo("TY24", "INCOMP")] TY24,
        [FluidInfo("Water", "INCOMP")] WaterIncomp,
        [FluidInfo("XLT", "INCOMP")] XLT,
        [FluidInfo("XLT2", "INCOMP")] XLT2,
        [FluidInfo("ZS10", "INCOMP")] ZS10,
        [FluidInfo("ZS25", "INCOMP")] ZS25,
        [FluidInfo("ZS40", "INCOMP")] ZS40,
        [FluidInfo("ZS45", "INCOMP")] ZS45,
        [FluidInfo("ZS55", "INCOMP")] ZS55,

        // Incompressible mass-based binary mixtures
        [FluidInfo("FRE", "INCOMP", false, Mix.Mass, 0.19, 0.5)] FRE,
        [FluidInfo("IceEA", "INCOMP", false, Mix.Mass, 0.05, 0.35)] IceEA,
        [FluidInfo("IceNA", "INCOMP", false, Mix.Mass, 0.05, 0.35)] IceNA,
        [FluidInfo("IcePG", "INCOMP", false, Mix.Mass, 0.05, 0.35)] IcePG,
        [FluidInfo("LiBr", "INCOMP", false, Mix.Mass, 0, 0.75)] LiBr,
        [FluidInfo("MAM", "INCOMP", false, Mix.Mass, 0, 0.3)] MAM,
        [FluidInfo("MAM2", "INCOMP", false, Mix.Mass, 0.078, 0.236)] MAM2,
        [FluidInfo("MCA", "INCOMP", false, Mix.Mass, 0, 0.3)] MCA,
        [FluidInfo("MCA2", "INCOMP", false, Mix.Mass, 0.09, 0.294)] MCA2,
        [FluidInfo("MEA", "INCOMP", false, Mix.Mass, 0, 0.6)] MEA,
        [FluidInfo("MEA2", "INCOMP", false, Mix.Mass, 0.11, 0.6)] MEA2,
        [FluidInfo("MEG", "INCOMP", false, Mix.Mass, 0, 0.6)] MEG,
        [FluidInfo("MEG2", "INCOMP", false, Mix.Mass, 0, 0.56)] MEG2,
        [FluidInfo("MGL", "INCOMP", false, Mix.Mass, 0, 0.6)] MGL,
        [FluidInfo("MGL2", "INCOMP", false, Mix.Mass, 0.195, 0.63)] MGL2,
        [FluidInfo("MITSW", "INCOMP", false, Mix.Mass, 0, 0.12)] MITSW,
        [FluidInfo("MKA", "INCOMP", false, Mix.Mass, 0, 0.45)] MKA,
        [FluidInfo("MKA2", "INCOMP", false, Mix.Mass, 0.11, 0.41)] MKA2,
        [FluidInfo("MKC", "INCOMP", false, Mix.Mass, 0, 0.4)] MKC,
        [FluidInfo("MKC2", "INCOMP", false, Mix.Mass, 0, 0.39)] MKC2,
        [FluidInfo("MKF", "INCOMP", false, Mix.Mass, 0, 0.48)] MKF,
        [FluidInfo("MLI", "INCOMP", false, Mix.Mass, 0, 0.24)] MLI,
        [FluidInfo("MMA", "INCOMP", false, Mix.Mass, 0, 0.6)] MMA,
        [FluidInfo("MMA2", "INCOMP", false, Mix.Mass, 0.078, 0.474)] MMA2,
        [FluidInfo("MMG", "INCOMP", false, Mix.Mass, 0, 0.3)] MMG,
        [FluidInfo("MMG2", "INCOMP", false, Mix.Mass, 0, 0.205)] MMG2,
        [FluidInfo("MNA", "INCOMP", false, Mix.Mass, 0, 0.23)] MNA,
        [FluidInfo("MNA2", "INCOMP", false, Mix.Mass, 0, 0.23)] MNA2,
        [FluidInfo("MPG", "INCOMP", false, Mix.Mass, 0, 0.6)] MPG,
        [FluidInfo("MPG2", "INCOMP", false, Mix.Mass, 0.15, 0.57)] MPG2,
        [FluidInfo("VCA", "INCOMP", false, Mix.Mass, 0.147, 0.299)] VCA,
        [FluidInfo("VKC", "INCOMP", false, Mix.Mass, 0.128, 0.389)] VKC,
        [FluidInfo("VMA", "INCOMP", false, Mix.Mass, 0.1, 0.9)] VMA,
        [FluidInfo("VMG", "INCOMP", false, Mix.Mass, 0.072, 0.206)] VMG,
        [FluidInfo("VNA", "INCOMP", false, Mix.Mass, 0.07, 0.231)] VNA,

        // Incompressible volume-based binary mixtures
        [FluidInfo("AEG", "INCOMP", false, Mix.Volume, 0.1, 0.6)] AEG,
        [FluidInfo("AKF", "INCOMP", false, Mix.Volume, 0.4)] AKF,
        [FluidInfo("AL", "INCOMP", false, Mix.Volume, 0.1, 0.6)] AL,
        [FluidInfo("AN", "INCOMP", false, Mix.Volume, 0.1, 0.6)] AN,
        [FluidInfo("APG", "INCOMP", false, Mix.Volume, 0.1, 0.6)] APG,
        [FluidInfo("GKN", "INCOMP", false, Mix.Volume, 0.1, 0.6)] GKN,
        [FluidInfo("PK2", "INCOMP", false, Mix.Volume, 0.3)] PK2,
        [FluidInfo("PKL", "INCOMP", false, Mix.Volume, 0.1, 0.6)] PKL,
        [FluidInfo("ZAC", "INCOMP", false, Mix.Volume, 0.06, 0.5)] ZAC,
        [FluidInfo("ZFC", "INCOMP", false, Mix.Volume, 0.3, 0.6)] ZFC,
        [FluidInfo("ZLC", "INCOMP", false, Mix.Volume, 0.3, 0.7)] ZLC,
        [FluidInfo("ZM", "INCOMP", false, Mix.Volume)] ZM,
        [FluidInfo("ZMC", "INCOMP", false, Mix.Volume, 0.3, 0.7)] ZMC
    }
}