//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CoolProp
{
public class AbstractState : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AbstractState(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AbstractState obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~AbstractState() => Dispose();

  public void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        swigCMemOwn = false;
        CPInvoke.delete_AbstractState(swigCPtr);
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
    global::System.GC.SuppressFinalize(this);
  }

  public static AbstractState factory(string backend, string fluid_names) {
    global::System.IntPtr cPtr = CPInvoke.AbstractState_factory__SWIG_0(backend, fluid_names);
    AbstractState ret = (cPtr == global::System.IntPtr.Zero) ? null : new AbstractState(cPtr, false);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public static AbstractState factory(string backend, StringVector fluid_names) {
    global::System.IntPtr cPtr = CPInvoke.AbstractState_factory__SWIG_1(backend, StringVector.getCPtr(fluid_names));
    AbstractState ret = (cPtr == global::System.IntPtr.Zero) ? null : new AbstractState(cPtr, false);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public void set_T(double T) {
    CPInvoke.AbstractState_set_T(swigCPtr, T);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public virtual string backend_name() {
    string ret = CPInvoke.AbstractState_backend_name(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool using_mole_fractions() {
    bool ret = CPInvoke.AbstractState_using_mole_fractions(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool using_mass_fractions() {
    bool ret = CPInvoke.AbstractState_using_mass_fractions(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool using_volu_fractions() {
    bool ret = CPInvoke.AbstractState_using_volu_fractions(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void set_reference_stateS(string reference_state) {
    CPInvoke.AbstractState_set_reference_stateS(swigCPtr, reference_state);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public virtual void set_reference_stateD(double T, double rhomolar, double hmolar0, double smolar0) {
    CPInvoke.AbstractState_set_reference_stateD(swigCPtr, T, rhomolar, hmolar0, smolar0);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public void set_mole_fractions(DoubleVector mole_fractions) {
    CPInvoke.AbstractState_set_mole_fractions(swigCPtr, DoubleVector.getCPtr(mole_fractions));
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public void set_mass_fractions(DoubleVector mass_fractions) {
    CPInvoke.AbstractState_set_mass_fractions(swigCPtr, DoubleVector.getCPtr(mass_fractions));
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public void set_volu_fractions(DoubleVector volu_fractions) {
    CPInvoke.AbstractState_set_volu_fractions(swigCPtr, DoubleVector.getCPtr(volu_fractions));
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public DoubleVector mole_fractions_liquid() {
    DoubleVector ret = new DoubleVector(CPInvoke.AbstractState_mole_fractions_liquid(swigCPtr), true);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public DoubleVector mole_fractions_vapor() {
    DoubleVector ret = new DoubleVector(CPInvoke.AbstractState_mole_fractions_vapor(swigCPtr), true);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual SWIGTYPE_p_std__vectorT_CoolPropDbl_t get_mole_fractions() {
    SWIGTYPE_p_std__vectorT_CoolPropDbl_t ret = new SWIGTYPE_p_std__vectorT_CoolPropDbl_t(CPInvoke.AbstractState_get_mole_fractions(swigCPtr), false);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual SWIGTYPE_p_std__vectorT_CoolPropDbl_t get_mass_fractions() {
    SWIGTYPE_p_std__vectorT_CoolPropDbl_t ret = new SWIGTYPE_p_std__vectorT_CoolPropDbl_t(CPInvoke.AbstractState_get_mass_fractions(swigCPtr), true);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void update(input_pairs input_pair, double Value1, double Value2) {
    CPInvoke.AbstractState_update(swigCPtr, (int)input_pair, Value1, Value2);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public virtual void update_with_guesses(input_pairs input_pair, double Value1, double Value2, GuessesStructure guesses) {
    CPInvoke.AbstractState_update_with_guesses(swigCPtr, (int)input_pair, Value1, Value2, GuessesStructure.getCPtr(guesses));
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public virtual bool available_in_high_level() {
    bool ret = CPInvoke.AbstractState_available_in_high_level(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string fluid_param_string(string arg0) {
    string ret = CPInvoke.AbstractState_fluid_param_string(swigCPtr, arg0);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public StringVector fluid_names() {
    StringVector ret = new StringVector(CPInvoke.AbstractState_fluid_names(swigCPtr), true);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double get_fluid_constant(uint i, Parameters param) {
    double ret = CPInvoke.AbstractState_get_fluid_constant(swigCPtr, i, (int)param);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void set_binary_interaction_double(string CAS1, string CAS2, string parameter, double value) {
    CPInvoke.AbstractState_set_binary_interaction_double__SWIG_0(swigCPtr, CAS1, CAS2, parameter, value);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public virtual void set_binary_interaction_double(uint i, uint j, string parameter, double value) {
    CPInvoke.AbstractState_set_binary_interaction_double__SWIG_1(swigCPtr, i, j, parameter, value);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public virtual void set_binary_interaction_string(string CAS1, string CAS2, string parameter, string value) {
    CPInvoke.AbstractState_set_binary_interaction_string__SWIG_0(swigCPtr, CAS1, CAS2, parameter, value);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public virtual void set_binary_interaction_string(uint i, uint j, string parameter, string value) {
    CPInvoke.AbstractState_set_binary_interaction_string__SWIG_1(swigCPtr, i, j, parameter, value);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public virtual double get_binary_interaction_double(string CAS1, string CAS2, string parameter) {
    double ret = CPInvoke.AbstractState_get_binary_interaction_double__SWIG_0(swigCPtr, CAS1, CAS2, parameter);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double get_binary_interaction_double(uint i, uint j, string parameter) {
    double ret = CPInvoke.AbstractState_get_binary_interaction_double__SWIG_1(swigCPtr, i, j, parameter);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string get_binary_interaction_string(string CAS1, string CAS2, string parameter) {
    string ret = CPInvoke.AbstractState_get_binary_interaction_string(swigCPtr, CAS1, CAS2, parameter);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void apply_simple_mixing_rule(uint i, uint j, string model) {
    CPInvoke.AbstractState_apply_simple_mixing_rule(swigCPtr, i, j, model);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public virtual void set_cubic_alpha_C(uint i, string parameter, double c1, double c2, double c3) {
    CPInvoke.AbstractState_set_cubic_alpha_C(swigCPtr, i, parameter, c1, c2, c3);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public virtual void set_fluid_parameter_double(uint i, string parameter, double value) {
    CPInvoke.AbstractState_set_fluid_parameter_double(swigCPtr, i, parameter, value);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public virtual double get_fluid_parameter_double(uint i, string parameter) {
    double ret = CPInvoke.AbstractState_get_fluid_parameter_double(swigCPtr, i, parameter);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool clear() {
    bool ret = CPInvoke.AbstractState_clear(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool clear_comp_change() {
    bool ret = CPInvoke.AbstractState_clear_comp_change(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual SimpleState get_reducing_state() {
    SimpleState ret = new SimpleState(CPInvoke.AbstractState_get_reducing_state(swigCPtr), false);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public SimpleState get_state(string state) {
    SimpleState ret = new SimpleState(CPInvoke.AbstractState_get_state(swigCPtr, state), false);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double Tmin() {
    double ret = CPInvoke.AbstractState_Tmin(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double Tmax() {
    double ret = CPInvoke.AbstractState_Tmax(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double pmax() {
    double ret = CPInvoke.AbstractState_pmax(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double Ttriple() {
    double ret = CPInvoke.AbstractState_Ttriple(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public phases phase() {
    phases ret = (phases)CPInvoke.AbstractState_phase(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public void specify_phase(phases phase) {
    CPInvoke.AbstractState_specify_phase(swigCPtr, (int)phase);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public void unspecify_phase() {
    CPInvoke.AbstractState_unspecify_phase(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public double T_critical() {
    double ret = CPInvoke.AbstractState_T_critical(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double p_critical() {
    double ret = CPInvoke.AbstractState_p_critical(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double rhomolar_critical() {
    double ret = CPInvoke.AbstractState_rhomolar_critical(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double rhomass_critical() {
    double ret = CPInvoke.AbstractState_rhomass_critical(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CoolProp__CriticalState_t all_critical_points() {
    SWIGTYPE_p_std__vectorT_CoolProp__CriticalState_t ret = new SWIGTYPE_p_std__vectorT_CoolProp__CriticalState_t(CPInvoke.AbstractState_all_critical_points(swigCPtr), true);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public void build_spinodal() {
    CPInvoke.AbstractState_build_spinodal(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public SpinodalData get_spinodal_data() {
    SpinodalData ret = new SpinodalData(CPInvoke.AbstractState_get_spinodal_data(swigCPtr), true);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public void criticality_contour_values(SWIGTYPE_p_double L1star, SWIGTYPE_p_double M1star) {
    CPInvoke.AbstractState_criticality_contour_values(swigCPtr, SWIGTYPE_p_double.getCPtr(L1star), SWIGTYPE_p_double.getCPtr(M1star));
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public double tangent_plane_distance(double T, double p, DoubleVector w, double rhomolar_guess) {
    double ret = CPInvoke.AbstractState_tangent_plane_distance__SWIG_0(swigCPtr, T, p, DoubleVector.getCPtr(w), rhomolar_guess);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double tangent_plane_distance(double T, double p, DoubleVector w) {
    double ret = CPInvoke.AbstractState_tangent_plane_distance__SWIG_1(swigCPtr, T, p, DoubleVector.getCPtr(w));
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double T_reducing() {
    double ret = CPInvoke.AbstractState_T_reducing(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double rhomolar_reducing() {
    double ret = CPInvoke.AbstractState_rhomolar_reducing(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double rhomass_reducing() {
    double ret = CPInvoke.AbstractState_rhomass_reducing(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double p_triple() {
    double ret = CPInvoke.AbstractState_p_triple(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public string name() {
    string ret = CPInvoke.AbstractState_name(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public string description() {
    string ret = CPInvoke.AbstractState_description(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double dipole_moment() {
    double ret = CPInvoke.AbstractState_dipole_moment(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double keyed_output(Parameters key) {
    double ret = CPInvoke.AbstractState_keyed_output(swigCPtr, (int)key);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double trivial_keyed_output(Parameters key) {
    double ret = CPInvoke.AbstractState_trivial_keyed_output(swigCPtr, (int)key);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double saturated_liquid_keyed_output(Parameters key) {
    double ret = CPInvoke.AbstractState_saturated_liquid_keyed_output(swigCPtr, (int)key);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double saturated_vapor_keyed_output(Parameters key) {
    double ret = CPInvoke.AbstractState_saturated_vapor_keyed_output(swigCPtr, (int)key);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double T() {
    double ret = CPInvoke.AbstractState_T(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double rhomolar() {
    double ret = CPInvoke.AbstractState_rhomolar(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double rhomass() {
    double ret = CPInvoke.AbstractState_rhomass(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double p() {
    double ret = CPInvoke.AbstractState_p(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double Q() {
    double ret = CPInvoke.AbstractState_Q(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double tau() {
    double ret = CPInvoke.AbstractState_tau(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double delta() {
    double ret = CPInvoke.AbstractState_delta(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double molar_mass() {
    double ret = CPInvoke.AbstractState_molar_mass(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double acentric_factor() {
    double ret = CPInvoke.AbstractState_acentric_factor(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double gas_constant() {
    double ret = CPInvoke.AbstractState_gas_constant(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double Bvirial() {
    double ret = CPInvoke.AbstractState_Bvirial(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double dBvirial_dT() {
    double ret = CPInvoke.AbstractState_dBvirial_dT(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double Cvirial() {
    double ret = CPInvoke.AbstractState_Cvirial(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double dCvirial_dT() {
    double ret = CPInvoke.AbstractState_dCvirial_dT(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double compressibility_factor() {
    double ret = CPInvoke.AbstractState_compressibility_factor(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double hmolar() {
    double ret = CPInvoke.AbstractState_hmolar(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double hmolar_residual() {
    double ret = CPInvoke.AbstractState_hmolar_residual(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double hmass() {
    double ret = CPInvoke.AbstractState_hmass(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double hmolar_excess() {
    double ret = CPInvoke.AbstractState_hmolar_excess(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double hmass_excess() {
    double ret = CPInvoke.AbstractState_hmass_excess(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double smolar() {
    double ret = CPInvoke.AbstractState_smolar(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double smolar_residual() {
    double ret = CPInvoke.AbstractState_smolar_residual(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double smass() {
    double ret = CPInvoke.AbstractState_smass(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double smolar_excess() {
    double ret = CPInvoke.AbstractState_smolar_excess(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double smass_excess() {
    double ret = CPInvoke.AbstractState_smass_excess(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double umolar() {
    double ret = CPInvoke.AbstractState_umolar(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double umass() {
    double ret = CPInvoke.AbstractState_umass(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double umolar_excess() {
    double ret = CPInvoke.AbstractState_umolar_excess(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double umass_excess() {
    double ret = CPInvoke.AbstractState_umass_excess(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double cpmolar() {
    double ret = CPInvoke.AbstractState_cpmolar(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double cpmass() {
    double ret = CPInvoke.AbstractState_cpmass(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double cp0molar() {
    double ret = CPInvoke.AbstractState_cp0molar(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double cp0mass() {
    double ret = CPInvoke.AbstractState_cp0mass(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double cvmolar() {
    double ret = CPInvoke.AbstractState_cvmolar(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double cvmass() {
    double ret = CPInvoke.AbstractState_cvmass(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double gibbsmolar() {
    double ret = CPInvoke.AbstractState_gibbsmolar(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double gibbsmolar_residual() {
    double ret = CPInvoke.AbstractState_gibbsmolar_residual(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double gibbsmass() {
    double ret = CPInvoke.AbstractState_gibbsmass(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double gibbsmolar_excess() {
    double ret = CPInvoke.AbstractState_gibbsmolar_excess(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double gibbsmass_excess() {
    double ret = CPInvoke.AbstractState_gibbsmass_excess(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double helmholtzmolar() {
    double ret = CPInvoke.AbstractState_helmholtzmolar(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double helmholtzmass() {
    double ret = CPInvoke.AbstractState_helmholtzmass(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double helmholtzmolar_excess() {
    double ret = CPInvoke.AbstractState_helmholtzmolar_excess(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double helmholtzmass_excess() {
    double ret = CPInvoke.AbstractState_helmholtzmass_excess(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double volumemolar_excess() {
    double ret = CPInvoke.AbstractState_volumemolar_excess(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double volumemass_excess() {
    double ret = CPInvoke.AbstractState_volumemass_excess(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double speed_sound() {
    double ret = CPInvoke.AbstractState_speed_sound(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double isothermal_compressibility() {
    double ret = CPInvoke.AbstractState_isothermal_compressibility(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double isobaric_expansion_coefficient() {
    double ret = CPInvoke.AbstractState_isobaric_expansion_coefficient(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double isentropic_expansion_coefficient() {
    double ret = CPInvoke.AbstractState_isentropic_expansion_coefficient(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double fugacity_coefficient(uint i) {
    double ret = CPInvoke.AbstractState_fugacity_coefficient(swigCPtr, i);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public DoubleVector fugacity_coefficients() {
    DoubleVector ret = new DoubleVector(CPInvoke.AbstractState_fugacity_coefficients(swigCPtr), true);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double fugacity(uint i) {
    double ret = CPInvoke.AbstractState_fugacity(swigCPtr, i);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double chemical_potential(uint i) {
    double ret = CPInvoke.AbstractState_chemical_potential(swigCPtr, i);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double fundamental_derivative_of_gas_dynamics() {
    double ret = CPInvoke.AbstractState_fundamental_derivative_of_gas_dynamics(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double PIP() {
    double ret = CPInvoke.AbstractState_PIP(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public void true_critical_point(SWIGTYPE_p_double T, SWIGTYPE_p_double rho) {
    CPInvoke.AbstractState_true_critical_point(swigCPtr, SWIGTYPE_p_double.getCPtr(T), SWIGTYPE_p_double.getCPtr(rho));
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public void ideal_curve(string type, DoubleVector T, DoubleVector p) {
    CPInvoke.AbstractState_ideal_curve(swigCPtr, type, DoubleVector.getCPtr(T), DoubleVector.getCPtr(p));
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public double first_partial_deriv(Parameters Of, Parameters Wrt, Parameters Constant) {
    double ret = CPInvoke.AbstractState_first_partial_deriv(swigCPtr, (int)Of, (int)Wrt, (int)Constant);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double second_partial_deriv(Parameters Of1, Parameters Wrt1, Parameters Constant1, Parameters Wrt2, Parameters Constant2) {
    double ret = CPInvoke.AbstractState_second_partial_deriv(swigCPtr, (int)Of1, (int)Wrt1, (int)Constant1, (int)Wrt2, (int)Constant2);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double first_saturation_deriv(Parameters Of1, Parameters Wrt1) {
    double ret = CPInvoke.AbstractState_first_saturation_deriv(swigCPtr, (int)Of1, (int)Wrt1);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double second_saturation_deriv(Parameters Of1, Parameters Wrt1, Parameters Wrt2) {
    double ret = CPInvoke.AbstractState_second_saturation_deriv(swigCPtr, (int)Of1, (int)Wrt1, (int)Wrt2);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double first_two_phase_deriv(Parameters Of, Parameters Wrt, Parameters Constant) {
    double ret = CPInvoke.AbstractState_first_two_phase_deriv(swigCPtr, (int)Of, (int)Wrt, (int)Constant);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double second_two_phase_deriv(Parameters Of, Parameters Wrt1, Parameters Constant1, Parameters Wrt2, Parameters Constant2) {
    double ret = CPInvoke.AbstractState_second_two_phase_deriv(swigCPtr, (int)Of, (int)Wrt1, (int)Constant1, (int)Wrt2, (int)Constant2);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double first_two_phase_deriv_splined(Parameters Of, Parameters Wrt, Parameters Constant, double x_end) {
    double ret = CPInvoke.AbstractState_first_two_phase_deriv_splined(swigCPtr, (int)Of, (int)Wrt, (int)Constant, x_end);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public void build_phase_envelope(string type) {
    CPInvoke.AbstractState_build_phase_envelope__SWIG_0(swigCPtr, type);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public void build_phase_envelope() {
    CPInvoke.AbstractState_build_phase_envelope__SWIG_1(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public PhaseEnvelopeData get_phase_envelope_data() {
    PhaseEnvelopeData ret = new PhaseEnvelopeData(CPInvoke.AbstractState_get_phase_envelope_data(swigCPtr), false);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool has_melting_line() {
    bool ret = CPInvoke.AbstractState_has_melting_line(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double melting_line(int param, int given, double value) {
    double ret = CPInvoke.AbstractState_melting_line(swigCPtr, param, given, value);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double saturation_ancillary(Parameters param, int Q, Parameters given, double value) {
    double ret = CPInvoke.AbstractState_saturation_ancillary(swigCPtr, (int)param, Q, (int)given, value);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double viscosity() {
    double ret = CPInvoke.AbstractState_viscosity(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public void viscosity_contributions(SWIGTYPE_p_CoolPropDbl dilute, SWIGTYPE_p_CoolPropDbl initial_density, SWIGTYPE_p_CoolPropDbl residual, SWIGTYPE_p_CoolPropDbl critical) {
    CPInvoke.AbstractState_viscosity_contributions(swigCPtr, SWIGTYPE_p_CoolPropDbl.getCPtr(dilute), SWIGTYPE_p_CoolPropDbl.getCPtr(initial_density), SWIGTYPE_p_CoolPropDbl.getCPtr(residual), SWIGTYPE_p_CoolPropDbl.getCPtr(critical));
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public double conductivity() {
    double ret = CPInvoke.AbstractState_conductivity(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public void conductivity_contributions(SWIGTYPE_p_CoolPropDbl dilute, SWIGTYPE_p_CoolPropDbl initial_density, SWIGTYPE_p_CoolPropDbl residual, SWIGTYPE_p_CoolPropDbl critical) {
    CPInvoke.AbstractState_conductivity_contributions(swigCPtr, SWIGTYPE_p_CoolPropDbl.getCPtr(dilute), SWIGTYPE_p_CoolPropDbl.getCPtr(initial_density), SWIGTYPE_p_CoolPropDbl.getCPtr(residual), SWIGTYPE_p_CoolPropDbl.getCPtr(critical));
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public double surface_tension() {
    double ret = CPInvoke.AbstractState_surface_tension(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double Prandtl() {
    double ret = CPInvoke.AbstractState_Prandtl(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public void conformal_state(string reference_fluid, SWIGTYPE_p_CoolPropDbl T, SWIGTYPE_p_CoolPropDbl rhomolar) {
    CPInvoke.AbstractState_conformal_state(swigCPtr, reference_fluid, SWIGTYPE_p_CoolPropDbl.getCPtr(T), SWIGTYPE_p_CoolPropDbl.getCPtr(rhomolar));
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public void change_EOS(uint i, string EOS_name) {
    CPInvoke.AbstractState_change_EOS(swigCPtr, i, EOS_name);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
  }

  public double alpha0() {
    double ret = CPInvoke.AbstractState_alpha0(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double dalpha0_dDelta() {
    double ret = CPInvoke.AbstractState_dalpha0_dDelta(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double dalpha0_dTau() {
    double ret = CPInvoke.AbstractState_dalpha0_dTau(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double d2alpha0_dDelta2() {
    double ret = CPInvoke.AbstractState_d2alpha0_dDelta2(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double d2alpha0_dDelta_dTau() {
    double ret = CPInvoke.AbstractState_d2alpha0_dDelta_dTau(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double d2alpha0_dTau2() {
    double ret = CPInvoke.AbstractState_d2alpha0_dTau2(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double d3alpha0_dTau3() {
    double ret = CPInvoke.AbstractState_d3alpha0_dTau3(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double d3alpha0_dDelta_dTau2() {
    double ret = CPInvoke.AbstractState_d3alpha0_dDelta_dTau2(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double d3alpha0_dDelta2_dTau() {
    double ret = CPInvoke.AbstractState_d3alpha0_dDelta2_dTau(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double d3alpha0_dDelta3() {
    double ret = CPInvoke.AbstractState_d3alpha0_dDelta3(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double alphar() {
    double ret = CPInvoke.AbstractState_alphar(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double dalphar_dDelta() {
    double ret = CPInvoke.AbstractState_dalphar_dDelta(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double dalphar_dTau() {
    double ret = CPInvoke.AbstractState_dalphar_dTau(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double d2alphar_dDelta2() {
    double ret = CPInvoke.AbstractState_d2alphar_dDelta2(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double d2alphar_dDelta_dTau() {
    double ret = CPInvoke.AbstractState_d2alphar_dDelta_dTau(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double d2alphar_dTau2() {
    double ret = CPInvoke.AbstractState_d2alphar_dTau2(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double d3alphar_dDelta3() {
    double ret = CPInvoke.AbstractState_d3alphar_dDelta3(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double d3alphar_dDelta2_dTau() {
    double ret = CPInvoke.AbstractState_d3alphar_dDelta2_dTau(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double d3alphar_dDelta_dTau2() {
    double ret = CPInvoke.AbstractState_d3alphar_dDelta_dTau2(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double d3alphar_dTau3() {
    double ret = CPInvoke.AbstractState_d3alphar_dTau3(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double d4alphar_dDelta4() {
    double ret = CPInvoke.AbstractState_d4alphar_dDelta4(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double d4alphar_dDelta3_dTau() {
    double ret = CPInvoke.AbstractState_d4alphar_dDelta3_dTau(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double d4alphar_dDelta2_dTau2() {
    double ret = CPInvoke.AbstractState_d4alphar_dDelta2_dTau2(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double d4alphar_dDelta_dTau3() {
    double ret = CPInvoke.AbstractState_d4alphar_dDelta_dTau3(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }

  public double d4alphar_dTau4() {
    double ret = CPInvoke.AbstractState_d4alphar_dTau4(swigCPtr);
    if (CPInvoke.SWIGPendingException.Pending) throw CPInvoke.SWIGPendingException.Retrieve();
    return ret;
  }
}
}