//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

// cSpell:disable
// ReSharper disable All

namespace CoolProp;

public class AbstractStateGenerator : global::System.IDisposable
{
    private global::System.Runtime.InteropServices.HandleRef swigCPtr;
    protected bool swigCMemOwn;

    internal AbstractStateGenerator(global::System.IntPtr cPtr, bool cMemoryOwn)
    {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
    }

    internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AbstractStateGenerator obj)
    {
        return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
    }

    internal static global::System.Runtime.InteropServices.HandleRef swigRelease(AbstractStateGenerator obj)
    {
        if (obj != null)
        {
            if (!obj.swigCMemOwn)
                throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
            global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
            obj.swigCMemOwn = false;
            obj.Dispose();
            return ptr;
        }
        else
        {
            return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        }
    }

    ~AbstractStateGenerator()
    {
        Dispose(false);
    }

    public void Dispose()
    {
        Dispose(true);
        global::System.GC.SuppressFinalize(this);
    }

    protected virtual void Dispose(bool disposing)
    {
        lock (this)
        {
            if (swigCPtr.Handle != global::System.IntPtr.Zero)
            {
                if (swigCMemOwn)
                {
                    swigCMemOwn = false;
                    CoolPropPINVOKE.delete_AbstractStateGenerator(swigCPtr);
                }
                swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
            }
        }
    }

    public virtual AbstractState get_AbstractState(StringVector fluid_names)
    {
        global::System.IntPtr cPtr = CoolPropPINVOKE.AbstractStateGenerator_get_AbstractState__SWIG_0(swigCPtr, StringVector.getCPtr(fluid_names));
        AbstractState ret = (cPtr == global::System.IntPtr.Zero) ? null : new AbstractState(cPtr, false);
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
        return ret;
    }

    public virtual AbstractState get_AbstractState(StringVector fluid_names, string options_json)
    {
        global::System.IntPtr cPtr = CoolPropPINVOKE.AbstractStateGenerator_get_AbstractState__SWIG_1(swigCPtr, StringVector.getCPtr(fluid_names), options_json);
        AbstractState ret = (cPtr == global::System.IntPtr.Zero) ? null : new AbstractState(cPtr, false);
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
        return ret;
    }

}
