//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

// cSpell:disable
// ReSharper disable All

namespace CoolProp;

public enum composition_types
{
    IFRAC_MASS,
    IFRAC_MOLE,
    IFRAC_VOLUME,
    IFRAC_UNDEFINED,
    IFRAC_PURE
}
