//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

// cSpell:disable
// ReSharper disable All

namespace CoolProp;

public class ConfigurationItem : global::System.IDisposable
{
    private global::System.Runtime.InteropServices.HandleRef swigCPtr;
    protected bool swigCMemOwn;

    internal ConfigurationItem(global::System.IntPtr cPtr, bool cMemoryOwn)
    {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
    }

    internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ConfigurationItem obj)
    {
        return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
    }

    internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ConfigurationItem obj)
    {
        if (obj != null)
        {
            if (!obj.swigCMemOwn)
                throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
            global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
            obj.swigCMemOwn = false;
            obj.Dispose();
            return ptr;
        }
        else
        {
            return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        }
    }

    ~ConfigurationItem()
    {
        Dispose(false);
    }

    public void Dispose()
    {
        Dispose(true);
        global::System.GC.SuppressFinalize(this);
    }

    protected virtual void Dispose(bool disposing)
    {
        lock (this)
        {
            if (swigCPtr.Handle != global::System.IntPtr.Zero)
            {
                if (swigCMemOwn)
                {
                    swigCMemOwn = false;
                    CoolPropPINVOKE.delete_ConfigurationItem(swigCPtr);
                }
                swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
            }
        }
    }

    public ConfigurationDataTypes get_type()
    {
        ConfigurationDataTypes ret = (ConfigurationDataTypes)CoolPropPINVOKE.ConfigurationItem_get_type(swigCPtr);
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
        return ret;
    }

    public ConfigurationItem(SWIGTYPE_p_configuration_keys key, bool val) : this(CoolPropPINVOKE.new_ConfigurationItem__SWIG_0(SWIGTYPE_p_configuration_keys.getCPtr(key), val), true)
    {
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    }

    public ConfigurationItem(SWIGTYPE_p_configuration_keys key, int val) : this(CoolPropPINVOKE.new_ConfigurationItem__SWIG_1(SWIGTYPE_p_configuration_keys.getCPtr(key), val), true)
    {
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    }

    public ConfigurationItem(SWIGTYPE_p_configuration_keys key, double val) : this(CoolPropPINVOKE.new_ConfigurationItem__SWIG_2(SWIGTYPE_p_configuration_keys.getCPtr(key), val), true)
    {
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    }

    public ConfigurationItem(SWIGTYPE_p_configuration_keys key, string val) : this(CoolPropPINVOKE.new_ConfigurationItem__SWIG_3(SWIGTYPE_p_configuration_keys.getCPtr(key), val), true)
    {
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    }

    public void set_bool(bool val)
    {
        CoolPropPINVOKE.ConfigurationItem_set_bool(swigCPtr, val);
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    }

    public void set_integer(int val)
    {
        CoolPropPINVOKE.ConfigurationItem_set_integer(swigCPtr, val);
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    }

    public void set_double(double val)
    {
        CoolPropPINVOKE.ConfigurationItem_set_double(swigCPtr, val);
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    }

    public void set_string(string val)
    {
        CoolPropPINVOKE.ConfigurationItem_set_string(swigCPtr, val);
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    }

    public SWIGTYPE_p_configuration_keys get_key()
    {
        SWIGTYPE_p_configuration_keys ret = new SWIGTYPE_p_configuration_keys(CoolPropPINVOKE.ConfigurationItem_get_key(swigCPtr), true);
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
        return ret;
    }

}
