//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

// cSpell:disable
// ReSharper disable All

namespace CoolProp;

public enum fast_evaluate_status : int
{
    fast_evaluate_ok = 0,
    fast_evaluate_out_of_range = 1,
    fast_evaluate_two_phase_disallowed = 2,
    fast_evaluate_unsupported_input = 3,
    fast_evaluate_unsupported_output = 4,
    fast_evaluate_internal_error = 5
}
