//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

// cSpell:disable
// ReSharper disable All

namespace CoolProp;

public enum input_pairs : int
{
    INPUT_PAIR_INVALID = 0,
    QT_INPUTS,
    QmassT_INPUTS,
    PQ_INPUTS,
    PQmass_INPUTS,
    QSmolar_INPUTS,
    QmassSmolar_INPUTS,
    QSmass_INPUTS,
    QmassSmass_INPUTS,
    HmolarQ_INPUTS,
    HmolarQmass_INPUTS,
    HmassQ_INPUTS,
    HmassQmass_INPUTS,
    DmolarQ_INPUTS,
    DmolarQmass_INPUTS,
    DmassQ_INPUTS,
    DmassQmass_INPUTS,
    PT_INPUTS,
    DmassT_INPUTS,
    DmolarT_INPUTS,
    HmolarT_INPUTS,
    HmassT_INPUTS,
    SmolarT_INPUTS,
    SmassT_INPUTS,
    TUmolar_INPUTS,
    TUmass_INPUTS,
    DmassP_INPUTS,
    DmolarP_INPUTS,
    HmassP_INPUTS,
    HmolarP_INPUTS,
    PSmass_INPUTS,
    PSmolar_INPUTS,
    PUmass_INPUTS,
    PUmolar_INPUTS,
    HmassSmass_INPUTS,
    HmolarSmolar_INPUTS,
    SmassUmass_INPUTS,
    SmolarUmolar_INPUTS,
    DmassHmass_INPUTS,
    DmolarHmolar_INPUTS,
    DmassSmass_INPUTS,
    DmolarSmolar_INPUTS,
    DmassUmass_INPUTS,
    DmolarUmolar_INPUTS
}
