//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

// cSpell:disable
// ReSharper disable All

namespace CoolProp;

public enum phases : int
{
    iphase_liquid,
    iphase_supercritical,
    iphase_supercritical_gas,
    iphase_supercritical_liquid,
    iphase_critical_point,
    iphase_gas,
    iphase_twophase,
    iphase_unknown,
    iphase_not_imposed
}
