//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

// cSpell:disable
// ReSharper disable All

namespace CoolProp;

public class SpinodalData : global::System.IDisposable
{
    private global::System.Runtime.InteropServices.HandleRef swigCPtr;
    protected bool swigCMemOwn;

    internal SpinodalData(global::System.IntPtr cPtr, bool cMemoryOwn)
    {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
    }

    internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SpinodalData obj)
    {
        return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
    }

    internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SpinodalData obj)
    {
        if (obj != null)
        {
            if (!obj.swigCMemOwn)
                throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
            global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
            obj.swigCMemOwn = false;
            obj.Dispose();
            return ptr;
        }
        else
        {
            return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        }
    }

    ~SpinodalData()
    {
        Dispose(false);
    }

    public void Dispose()
    {
        Dispose(true);
        global::System.GC.SuppressFinalize(this);
    }

    protected virtual void Dispose(bool disposing)
    {
        lock (this)
        {
            if (swigCPtr.Handle != global::System.IntPtr.Zero)
            {
                if (swigCMemOwn)
                {
                    swigCMemOwn = false;
                    CoolPropPINVOKE.delete_SpinodalData(swigCPtr);
                }
                swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
            }
        }
    }

    public DoubleVector tau
    {
        set
        {
            CoolPropPINVOKE.SpinodalData_tau_set(swigCPtr, DoubleVector.getCPtr(value));
            if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
        }
        get
        {
            global::System.IntPtr cPtr = CoolPropPINVOKE.SpinodalData_tau_get(swigCPtr);
            DoubleVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DoubleVector(cPtr, false);
            if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
            return ret;
        }
    }

    public DoubleVector delta
    {
        set
        {
            CoolPropPINVOKE.SpinodalData_delta_set(swigCPtr, DoubleVector.getCPtr(value));
            if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
        }
        get
        {
            global::System.IntPtr cPtr = CoolPropPINVOKE.SpinodalData_delta_get(swigCPtr);
            DoubleVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DoubleVector(cPtr, false);
            if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
            return ret;
        }
    }

    public DoubleVector M1
    {
        set
        {
            CoolPropPINVOKE.SpinodalData_M1_set(swigCPtr, DoubleVector.getCPtr(value));
            if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
        }
        get
        {
            global::System.IntPtr cPtr = CoolPropPINVOKE.SpinodalData_M1_get(swigCPtr);
            DoubleVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DoubleVector(cPtr, false);
            if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
            return ret;
        }
    }

    public SpinodalData() : this(CoolPropPINVOKE.new_SpinodalData(), true)
    {
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    }

}
