//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

// cSpell:disable
// ReSharper disable All

namespace CoolProp;

public class SsatSimpleState : SimpleState
{
    private global::System.Runtime.InteropServices.HandleRef swigCPtr;

    internal SsatSimpleState(global::System.IntPtr cPtr, bool cMemoryOwn) : base(CoolPropPINVOKE.SsatSimpleState_SWIGUpcast(cPtr), cMemoryOwn)
    {
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
    }

    internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SsatSimpleState obj)
    {
        return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
    }

    internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SsatSimpleState obj)
    {
        if (obj != null)
        {
            if (!obj.swigCMemOwn)
                throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
            global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
            obj.swigCMemOwn = false;
            obj.Dispose();
            return ptr;
        }
        else
        {
            return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        }
    }

    protected override void Dispose(bool disposing)
    {
        lock (this)
        {
            if (swigCPtr.Handle != global::System.IntPtr.Zero)
            {
                if (swigCMemOwn)
                {
                    swigCMemOwn = false;
                    CoolPropPINVOKE.delete_SsatSimpleState(swigCPtr);
                }
                swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
            }
            base.Dispose(disposing);
        }
    }

    public SsatSimpleState.SsatSimpleStateEnum exists
    {
        set
        {
            CoolPropPINVOKE.SsatSimpleState_exists_set(swigCPtr, (int)value);
            if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
        }
        get
        {
            SsatSimpleState.SsatSimpleStateEnum ret = (SsatSimpleState.SsatSimpleStateEnum)CoolPropPINVOKE.SsatSimpleState_exists_get(swigCPtr);
            if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
            return ret;
        }
    }

    public SsatSimpleState() : this(CoolPropPINVOKE.new_SsatSimpleState(), true)
    {
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    }

    public enum SsatSimpleStateEnum
    {
        SSAT_MAX_NOT_SET = 0,
        SSAT_MAX_DOESNT_EXIST,
        SSAT_MAX_DOES_EXIST
    }

}
