name: Build & Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-tests:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            4.8.x
            6.0.x
            7.0.x
      - name: Setup .NET Framework
        if: ${{ matrix.os }} == windows-latest
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 4.8.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        if: ${{ matrix.os }} == ubuntu-latest
        run: dotnet test --no-build
      - name: Test with coverage
        if: ${{ matrix.os }} == windows-latest
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --settings coverlet.runsettings
      - name: Upload coverage to Codecov
        if: ${{ matrix.os }} == windows-latest
        uses: codecov/codecov-action@v3