name: Build & Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-tests:
    name: Build & Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2022, ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --settings coverlet.runsettings
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  publish:
    if: ${{ github.event_name == 'push' }}
    needs: build-tests
    name: Publish to NuGet
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Publish on version change
        id: publish_nuget
        continue-on-error: true
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: SharpProp/SharpProp.csproj
          PACKAGE_NAME: SharpProp
          VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}