name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  csharpier:
    name: Check with CSharpier
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            9.0.x
            10.0.x
      - name: Restore tools
        run: dotnet tool restore
      - name: Check code style
        run: dotnet csharpier check .

  tests:
    needs: [csharpier]
    name: Tests / ${{ matrix.rid }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04-arm
            rid: linux-arm64
          - os: ubuntu-latest
            rid: linux-x64
          - os: macos-latest
            rid: osx-arm64
          - os: macos-15-intel
            rid: osx-x64
          - os: windows-11-arm
            rid: win-arm64
          - os: windows-latest
            rid: win-x64

    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            9.0.x
            10.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

  coverage:
    needs: [csharpier, tests]
    name: Code coverage
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            9.0.x
            10.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Generate coverage report
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --settings coverlet.runsettings
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
