name: Publish to NuGet

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  publish:
    name: Publish to NuGet
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Pack
        run: dotnet pack --no-build --configuration Release --property PackageOutputPath=${GITHUB_WORKSPACE}/nuget
      - name: Publish to NuGet
        run: dotnet nuget push ./nuget/*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
